version: '3.4'
services:
  pgservice:
    image: postgres:latest
    # The `env_file` tag allows us to declare an environment file
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: postgres
      POSTGRES_DB: soundbox
    ports:
      - 5432:5432
    volumes:
      - soundbox-db:/var/lib/postgresql/data
    networks:
      - soundboxNetwork

  soundbox:
    build:
      context: .
    environment:
      DB_HOST: pgservice
      DB_USER: postgres
      DB_PASSWORD: pg1234
      DB_NAME: soundbox
    restart: unless-stopped
    depends_on:
      - pgservice
    ports:
      - 3000:3000
    networks:
      - soundboxNetwork
    stdin_open: true
    tty: true
    # binding working dir
    # so the app is keeping track of changes made
    # to any file within the container, like rfid_logger.txt changes
    # from rfid service
    volumes:
          - type: bind
            source: .
            target: /usr/src/app

volumes:
  soundbox-db:

networks:
  soundboxNetwork:
    external: false
