version: '3.4'
services:
  pgservice:
    image: postgres:latest
    # The `env_file` tag allows us to declare an environment file
    environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
    volumes:
      - soundbox-db:/var/lib/postgresql/data
    networks:
      - soundboxNetwork

  soundbox:
    build:
      context: .
    env_file:
      - .env # The name of your environment file (the one at the repository root)
    restart: unless-stopped
    depends_on:
      - pgservice
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    networks:
      - soundboxNetwork
    stdin_open: true
    tty: true

volumes:
  soundbox-db:

networks:
  soundboxNetwork:
    external: false
